'''
exceptions.py: exceptions defined by Microarchiver

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2019-2020 by the California Institute of Technology.  This code
is open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''


# Base class.
# .............................................................................
# The base class makes it possible to use a single test to distinguish between
# exceptions generated by Microarchiver & those generated by something else.

class MicroarchiverException(Exception):
    '''Base class for Microarchiver exceptions.'''
    pass


# Exception classes.
# .............................................................................

class InternalError(Exception):
    '''Unrecoverable problem involving Microarchiver itself.'''
    pass
